sudo: required
services:
  - docker
before_install:
  - sudo apt-get install jq
env:
- ADDON="flicd"
addons:
  adb:
    repository: hassio-addons/flicd
    target: flicd
image: hassioaddons/example-{arch}
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./build.sh "$ADDON" "$ARCH"

# vim: set ft=yaml et ts=2 sw=2 :
